### ISSUE TITLE
MySQL pool connection closing or releasing not added

### ISSUE THREAD

**Issue by tech-srinath** [Jon-Peppinck/angular-node-mysql-crud#5]
Hey there, I'm trying to use your code logic for my Nodejs express crud. I've been getting an error trying to close the connection or releasing the pool after every query execution.
I've noted that you've not added a connection release statement after query execution. Is it necessary that we add release connection function after a pool connection?

**Comment by Jon-Peppinck** [comment]
Hi @tech-srinath thank you for your comment. My understanding is that if we are creating an API that is constantly listening for requests on the server it is more efficient to have a 'connection pool' that can respond to requests, and since the server is always running, we don't want to end the connection - you could however end it by using db.end(). This is opposed to creating a connection (which needs to connect to the database each time) and then terminating the connection for each request. You can read more about it [here](https://www.npmjs.com/package/mysql2#using-connection-pools)
